new files
git-svn-id: svn://svn.savannah.nongnu.org/osip/trunk/osip@408 a617929b-4c5a-41d8-b177-2eda7db2ca6c

diff --git a/src/test/tst b/src/test/tst
--- a/src/test/tst
+++ b/src/test/tst
@@ -12,7 +12,7 @@ ok=0
 nok=0
 
 i=0
-while [ $i -lt 96 ]
+while [ $i -lt 87 ]
 do
 set +x
 #  mpatrol -C -S -L -j -d --list -p -t --use-debug ./test/torture_test $1 $i $2 $3
@@ -21,7 +21,7 @@ set +x
        echo "checking sip$i : passed";
        ok=`expr $ok + 1`;
    else
-       echo "checking sip" $i": failed";
+       echo "checking sip$i : failed";
        nok=`expr $nok + 1`
    fi;
 
@@ -29,23 +29,32 @@ set +x
 
 done
 
-echo "number of messages:   $i (XX expected)"
-echo "correct messages  :   $ok (XX expected)"
-echo "malformed messages:   $nok (XX expected)"
+echo "checked well formed messages:   $i"
+echo "errors                      :   $nok"
 
-#echo "=="
-#echo "== Test for \\n (CR) and \\r (LF) instead of \\r\\n (CRLF)"
-#echo "== Data files from ./conf/torture_msgs"
-#echo "=="
+ok=0
+nok=0
 
+i=0
+while [ $i -lt 9 ]
+do
+set +x
+#  mpatrol -C -S -L -j -d --list -p -t --use-debug ./test/torture_test $1 $i $2 $3
+   ./torture_test ./res/sip-malformed$i 0 $1
+   if [ "$?" -eq 0 ]; then
+       echo "checking sip$i : passed";
+       ok=`expr $ok + 1`;
+   else
+       echo "checking sip$i : failed";
+       nok=`expr $nok + 1`
+   fi;
 
-#i=0
-#while [ $i -lt 93 ]
-#do
-#set -x
-#    ./torture_test conf/torture_msgs2 $i $2 $3
-#set +x
-#    i=`expr $i + 1`
-#done
+   i=`expr $i + 1`
+
+done
+
+echo "checked malformed messages:   $i"
+echo "errors                    :   $ok"
+
 
 
