* optimize list search: use iterator  * improve/update autotools (./configure and options, Makefile.am, ax_thread.m4...)  * verify a URI scheme only contains allowed char  * improve make check (test unit) to make it clear about the results expected.

diff --git a/src/test/tst b/src/test/tst
--- a/src/test/tst
+++ b/src/test/tst
@@ -10,53 +10,46 @@
 
 ok=0
 nok=0
+total=0
 
 i=0
-while [ $i -lt 89 ]
+while [ $i -lt 88 ]
 do
-set +x
+    filename=$1/sip$i
    #mpatrol -C -S -L -d --list -p --use-debug ./torture_test $1/sip$i 0 $2
-   ./torture_test $1/sip$i 0 $2
-
-   code=$?
+    ./torture_test $filename $2
+    code=$?
    if [ "$code" -eq 0 ]; then
-       echo "checking sip$i : passed";
        ok=`expr $ok + 1`;
    else
-       echo "checking sip$i : failed ($code)";
        nok=`expr $nok + 1`
    fi;
-
    i=`expr $i + 1`
-
+   total=`expr $total + 1`
 done
 
-echo "checked well formed messages:   $i"
-echo "errors                      :   $nok"
+i=0
+while [ $i -lt 13 ]
+do
+    filename=$1/sip-malformed$i
+    #   #mpatrol -C -S -L -d --list -p --use-debug ./torture_test $1/sip-malformed$i 0 $2
+    ./torture_test $filename $2
+   code=$?
+   if [ "$code" -eq 0 ]; then
+       ok=`expr $ok + 1`;
+   else
+       nok=`expr $nok + 1`
+   fi;
+   i=`expr $i + 1`
+   total=`expr $total + 1`
+done
+#
 
-#ok=0
-#nok=0
-#
-#i=0
-#while [ $i -lt 9 ]
-#do
-#set +x
-#   #mpatrol -C -S -L -d --list -p --use-debug ./torture_test ./res/sip-malformed$i 0 $1
-#   ./torture_test $1/sip-malformed$i 0 $2
-#   if [ "$?" -eq 0 ]; then
-#       echo "checking sip$i : passed";
-#       ok=`expr $ok + 1`;
-#   else
-#       echo "checking sip$i : failed";
-#       nok=`expr $nok + 1`
-#   fi;
-#
-#   i=`expr $i + 1`
-#
-#done
-#
-#echo "checked malformed messages:   $i"
-#echo "errors                    :   $ok"
+echo "unit testing total :   $total"
+echo "unit testing passed:   $ok"
+echo "unit testing failed:   $nok"
+
+
 
 
 
